package integration;

import integration.impl.DefaultIntegrator;
import integration.impl.MoodleDbIntegrator;
import integration.impl.MoodleIntegrator;
import storage.StorageFactory;

import java.util.HashMap;
import java.util.Map;
import java.util.NoSuchElementException;

public class Integrator {

    private static final String INTEGRATOR_TYPE = getProperty("INTEGRATOR_TYPE");

    private static volatile IIntegrator iIntegrator = null;

    public static IIntegrator instance() {
        if (iIntegrator == null)
            synchronized (StorageFactory.class) {
                if (iIntegrator == null) {
                    iIntegrator = getIntegrator();
                }
            }
        return iIntegrator;
    }

    private static IIntegrator getIntegrator() {
        System.out.println("Integrator.getIntegrator() INTEGRATOR_TYPE=" + INTEGRATOR_TYPE);
        switch (INTEGRATOR_TYPE != null ? INTEGRATOR_TYPE.toUpperCase() : "") {
            case "MOODLE":
                return new MoodleIntegrator();
            case "MOODLEDB":
                return new MoodleDbIntegrator();
            case "":
                return new DefaultIntegrator();
            default:
                throw new NoSuchElementException("Environment variable INTEGRATOR_TYPE=" + INTEGRATOR_TYPE + " have unsupported value");
        }
    }

    public static String getProperty(String name) {
        String prop = System.getProperty(name);
        return prop != null ? prop : System.getenv(name);
    }

    public static Integer getIntProperty(String name) {
        String prop = getProperty(name);
        return prop != null ? Integer.parseInt(prop) : null;
    }

    public static Integer getMoodleTzOffset(String tz) {
        return Integrator.MOODLE_TZ.get(tz);
    }

    private static final Map<String, Integer> MOODLE_TZ = new HashMap<>(1103);

    static {
        // from https://download.moodle.org/timezone/
        // Excel "MoodleIntegrator-java-init.xlsx" will help to refresh it
        MOODLE_TZ.put("Africa/Algiers", 60);
        MOODLE_TZ.put("Atlantic/Cape_Verde", -60);
        MOODLE_TZ.put("Africa/Ndjamena", 60);
        MOODLE_TZ.put("Africa/Abidjan", 0);
        MOODLE_TZ.put("Africa/Cairo", 120);
        MOODLE_TZ.put("Africa/Accra", 0);
        MOODLE_TZ.put("Africa/Bissau", 0);
        MOODLE_TZ.put("Africa/Nairobi", 180);
        MOODLE_TZ.put("Africa/Monrovia", 0);
        MOODLE_TZ.put("Africa/Tripoli", 120);
        MOODLE_TZ.put("Indian/Mauritius", 240);
        MOODLE_TZ.put("Africa/Casablanca", 0);
        MOODLE_TZ.put("Africa/El_Aaiun", 0);
        MOODLE_TZ.put("Africa/Maputo", 120);
        MOODLE_TZ.put("Africa/Windhoek", 60);
        MOODLE_TZ.put("Africa/Lagos", 60);
        MOODLE_TZ.put("Indian/Reunion", 240);
        MOODLE_TZ.put("Indian/Mahe", 240);
        MOODLE_TZ.put("Africa/Johannesburg", 120);
        MOODLE_TZ.put("Africa/Khartoum", 180);
        MOODLE_TZ.put("Africa/Tunis", 60);
        MOODLE_TZ.put("Antarctica/Casey", 660);
        MOODLE_TZ.put("Antarctica/Davis", 420);
        MOODLE_TZ.put("Antarctica/Mawson", 300);
        MOODLE_TZ.put("Indian/Kerguelen", 300);
        MOODLE_TZ.put("Antarctica/DumontDUrville", 600);
        MOODLE_TZ.put("Antarctica/Syowa", 180);
        MOODLE_TZ.put("Antarctica/Troll", 0);
        MOODLE_TZ.put("Antarctica/Vostok", 360);
        MOODLE_TZ.put("Antarctica/Rothera", -180);
        MOODLE_TZ.put("Asia/Kabul", 270);
        MOODLE_TZ.put("Asia/Yerevan", 240);
        MOODLE_TZ.put("Asia/Baku", 240);
        MOODLE_TZ.put("Asia/Dhaka", 360);
        MOODLE_TZ.put("Asia/Thimphu", 360);
        MOODLE_TZ.put("Indian/Chagos", 360);
        MOODLE_TZ.put("Asia/Brunei", 480);
        MOODLE_TZ.put("Asia/Yangon", 390);
        MOODLE_TZ.put("Asia/Shanghai", 480);
        MOODLE_TZ.put("Asia/Urumqi", 360);
        MOODLE_TZ.put("Asia/Hong_Kong", 480);
        MOODLE_TZ.put("Asia/Taipei", 480);
        MOODLE_TZ.put("Asia/Macau", 480);
        MOODLE_TZ.put("Asia/Nicosia", 120);
        MOODLE_TZ.put("Asia/Famagusta", 180);
        MOODLE_TZ.put("Asia/Tbilisi", 240);
        MOODLE_TZ.put("Asia/Dili", 540);
        MOODLE_TZ.put("Asia/Kolkata", 330);
        MOODLE_TZ.put("Asia/Jakarta", 420);
        MOODLE_TZ.put("Asia/Pontianak", 420);
        MOODLE_TZ.put("Asia/Makassar", 480);
        MOODLE_TZ.put("Asia/Jayapura", 540);
        MOODLE_TZ.put("Asia/Tehran", 210);
        MOODLE_TZ.put("Asia/Baghdad", 180);
        MOODLE_TZ.put("Asia/Jerusalem", 120);
        MOODLE_TZ.put("Asia/Tokyo", 540);
        MOODLE_TZ.put("Asia/Amman", 120);
        MOODLE_TZ.put("Asia/Almaty", 360);
        MOODLE_TZ.put("Asia/Qyzylorda", 360);
        MOODLE_TZ.put("Asia/Aqtobe", 300);
        MOODLE_TZ.put("Asia/Aqtau", 300);
        MOODLE_TZ.put("Asia/Atyrau", 300);
        MOODLE_TZ.put("Asia/Oral", 300);
        MOODLE_TZ.put("Asia/Bishkek", 360);
        MOODLE_TZ.put("Asia/Seoul", 540);
        MOODLE_TZ.put("Asia/Pyongyang", 510);
        MOODLE_TZ.put("Asia/Beirut", 120);
        MOODLE_TZ.put("Asia/Kuala_Lumpur", 480);
        MOODLE_TZ.put("Asia/Kuching", 480);
        MOODLE_TZ.put("Indian/Maldives", 300);
        MOODLE_TZ.put("Asia/Hovd", 420);
        MOODLE_TZ.put("Asia/Ulaanbaatar", 480);
        MOODLE_TZ.put("Asia/Choibalsan", 480);
        MOODLE_TZ.put("Asia/Kathmandu", 345);
        MOODLE_TZ.put("Asia/Karachi", 300);
        MOODLE_TZ.put("Asia/Gaza", 120);
        MOODLE_TZ.put("Asia/Hebron", 120);
        MOODLE_TZ.put("Asia/Manila", 480);
        MOODLE_TZ.put("Asia/Qatar", 180);
        MOODLE_TZ.put("Asia/Riyadh", 180);
        MOODLE_TZ.put("Asia/Singapore", 480);
        MOODLE_TZ.put("Asia/Colombo", 330);
        MOODLE_TZ.put("Asia/Damascus", 120);
        MOODLE_TZ.put("Asia/Dushanbe", 300);
        MOODLE_TZ.put("Asia/Bangkok", 420);
        MOODLE_TZ.put("Asia/Ashgabat", 300);
        MOODLE_TZ.put("Asia/Dubai", 240);
        MOODLE_TZ.put("Asia/Samarkand", 300);
        MOODLE_TZ.put("Asia/Tashkent", 300);
        MOODLE_TZ.put("Asia/Ho_Chi_Minh", 420);
        MOODLE_TZ.put("Australia/Darwin", 570);
        MOODLE_TZ.put("Australia/Perth", 480);
        MOODLE_TZ.put("Australia/Eucla", 525);
        MOODLE_TZ.put("Australia/Brisbane", 600);
        MOODLE_TZ.put("Australia/Lindeman", 600);
        MOODLE_TZ.put("Australia/Adelaide", 570);
        MOODLE_TZ.put("Australia/Hobart", 600);
        MOODLE_TZ.put("Australia/Currie", 600);
        MOODLE_TZ.put("Australia/Melbourne", 600);
        MOODLE_TZ.put("Australia/Sydney", 600);
        MOODLE_TZ.put("Australia/Broken_Hill", 570);
        MOODLE_TZ.put("Australia/Lord_Howe", 630);
        MOODLE_TZ.put("Antarctica/Macquarie", 660);
        MOODLE_TZ.put("Indian/Christmas", 420);
        MOODLE_TZ.put("Indian/Cocos", 390);
        MOODLE_TZ.put("Pacific/Fiji", 720);
        MOODLE_TZ.put("Pacific/Gambier", -540);
        MOODLE_TZ.put("Pacific/Marquesas", -570);
        MOODLE_TZ.put("Pacific/Tahiti", -600);
        MOODLE_TZ.put("Pacific/Guam", 600);
        MOODLE_TZ.put("Pacific/Tarawa", 720);
        MOODLE_TZ.put("Pacific/Enderbury", 780);
        MOODLE_TZ.put("Pacific/Kiritimati", 840);
        MOODLE_TZ.put("Pacific/Majuro", 720);
        MOODLE_TZ.put("Pacific/Kwajalein", 720);
        MOODLE_TZ.put("Pacific/Chuuk", 600);
        MOODLE_TZ.put("Pacific/Pohnpei", 660);
        MOODLE_TZ.put("Pacific/Kosrae", 660);
        MOODLE_TZ.put("Pacific/Nauru", 720);
        MOODLE_TZ.put("Pacific/Noumea", 660);
        MOODLE_TZ.put("Pacific/Auckland", 720);
        MOODLE_TZ.put("Pacific/Chatham", 765);
        MOODLE_TZ.put("Pacific/Rarotonga", -600);
        MOODLE_TZ.put("Pacific/Niue", -660);
        MOODLE_TZ.put("Pacific/Norfolk", 660);
        MOODLE_TZ.put("Pacific/Palau", 540);
        MOODLE_TZ.put("Pacific/Port_Moresby", 600);
        MOODLE_TZ.put("Pacific/Bougainville", 660);
        MOODLE_TZ.put("Pacific/Pitcairn", -480);
        MOODLE_TZ.put("Pacific/Pago_Pago", -660);
        MOODLE_TZ.put("Pacific/Apia", 780);
        MOODLE_TZ.put("Pacific/Guadalcanal", 660);
        MOODLE_TZ.put("Pacific/Fakaofo", 780);
        MOODLE_TZ.put("Pacific/Tongatapu", 780);
        MOODLE_TZ.put("Pacific/Funafuti", 720);
        MOODLE_TZ.put("Pacific/Wake", 720);
        MOODLE_TZ.put("Pacific/Efate", 660);
        MOODLE_TZ.put("Pacific/Wallis", 720);
        MOODLE_TZ.put("Europe/London", 0);
        MOODLE_TZ.put("Europe/Dublin", 0);
        MOODLE_TZ.put("WET", 0);
        MOODLE_TZ.put("CET", 60);
        MOODLE_TZ.put("MET", 60);
        MOODLE_TZ.put("EET", 120);
        MOODLE_TZ.put("Europe/Tirane", 60);
        MOODLE_TZ.put("Europe/Andorra", 60);
        MOODLE_TZ.put("Europe/Vienna", 60);
        MOODLE_TZ.put("Europe/Minsk", 180);
        MOODLE_TZ.put("Europe/Brussels", 60);
        MOODLE_TZ.put("Europe/Sofia", 120);
        MOODLE_TZ.put("Europe/Prague", 60);
        MOODLE_TZ.put("Europe/Copenhagen", 60);
        MOODLE_TZ.put("Atlantic/Faroe", 0);
        MOODLE_TZ.put("America/Danmarkshavn", 0);
        MOODLE_TZ.put("America/Scoresbysund", -60);
        MOODLE_TZ.put("America/Godthab", -180);
        MOODLE_TZ.put("America/Thule", -240);
        MOODLE_TZ.put("Europe/Tallinn", 120);
        MOODLE_TZ.put("Europe/Helsinki", 120);
        MOODLE_TZ.put("Europe/Paris", 60);
        MOODLE_TZ.put("Europe/Berlin", 60);
        MOODLE_TZ.put("Europe/Gibraltar", 60);
        MOODLE_TZ.put("Europe/Athens", 120);
        MOODLE_TZ.put("Europe/Budapest", 60);
        MOODLE_TZ.put("Atlantic/Reykjavik", 0);
        MOODLE_TZ.put("Europe/Rome", 60);
        MOODLE_TZ.put("Europe/Riga", 120);
        MOODLE_TZ.put("Europe/Vilnius", 120);
        MOODLE_TZ.put("Europe/Luxembourg", 60);
        MOODLE_TZ.put("Europe/Malta", 60);
        MOODLE_TZ.put("Europe/Chisinau", 120);
        MOODLE_TZ.put("Europe/Monaco", 60);
        MOODLE_TZ.put("Europe/Amsterdam", 60);
        MOODLE_TZ.put("Europe/Oslo", 60);
        MOODLE_TZ.put("Europe/Warsaw", 60);
        MOODLE_TZ.put("Europe/Lisbon", 0);
        MOODLE_TZ.put("Atlantic/Azores", -60);
        MOODLE_TZ.put("Atlantic/Madeira", 0);
        MOODLE_TZ.put("Europe/Bucharest", 120);
        MOODLE_TZ.put("Europe/Kaliningrad", 120);
        MOODLE_TZ.put("Europe/Moscow", 180);
        MOODLE_TZ.put("Europe/Simferopol", 180);
        MOODLE_TZ.put("Europe/Astrakhan", 240);
        MOODLE_TZ.put("Europe/Volgograd", 180);
        MOODLE_TZ.put("Europe/Saratov", 240);
        MOODLE_TZ.put("Europe/Kirov", 180);
        MOODLE_TZ.put("Europe/Samara", 240);
        MOODLE_TZ.put("Europe/Ulyanovsk", 240);
        MOODLE_TZ.put("Asia/Yekaterinburg", 300);
        MOODLE_TZ.put("Asia/Omsk", 360);
        MOODLE_TZ.put("Asia/Barnaul", 420);
        MOODLE_TZ.put("Asia/Novosibirsk", 420);
        MOODLE_TZ.put("Asia/Tomsk", 420);
        MOODLE_TZ.put("Asia/Novokuznetsk", 420);
        MOODLE_TZ.put("Asia/Krasnoyarsk", 420);
        MOODLE_TZ.put("Asia/Irkutsk", 480);
        MOODLE_TZ.put("Asia/Chita", 540);
        MOODLE_TZ.put("Asia/Yakutsk", 540);
        MOODLE_TZ.put("Asia/Vladivostok", 600);
        MOODLE_TZ.put("Asia/Khandyga", 540);
        MOODLE_TZ.put("Asia/Sakhalin", 660);
        MOODLE_TZ.put("Asia/Magadan", 660);
        MOODLE_TZ.put("Asia/Srednekolymsk", 660);
        MOODLE_TZ.put("Asia/Ust-Nera", 600);
        MOODLE_TZ.put("Asia/Kamchatka", 720);
        MOODLE_TZ.put("Asia/Anadyr", 720);
        MOODLE_TZ.put("Europe/Belgrade", 60);
        MOODLE_TZ.put("Europe/Madrid", 60);
        MOODLE_TZ.put("Africa/Ceuta", 60);
        MOODLE_TZ.put("Atlantic/Canary", 0);
        MOODLE_TZ.put("Europe/Stockholm", 60);
        MOODLE_TZ.put("Europe/Zurich", 60);
        MOODLE_TZ.put("Europe/Istanbul", 180);
        MOODLE_TZ.put("Europe/Kiev", 120);
        MOODLE_TZ.put("Europe/Uzhgorod", 120);
        MOODLE_TZ.put("Europe/Zaporozhye", 120);
        MOODLE_TZ.put("EST", -300);
        MOODLE_TZ.put("MST", -420);
        MOODLE_TZ.put("HST", -600);
        MOODLE_TZ.put("EST5EDT", -300);
        MOODLE_TZ.put("CST6CDT", -360);
        MOODLE_TZ.put("MST7MDT", -420);
        MOODLE_TZ.put("PST8PDT", -480);
        MOODLE_TZ.put("America/New_York", -300);
        MOODLE_TZ.put("America/Chicago", -360);
        MOODLE_TZ.put("America/North_Dakota/Center", -360);
        MOODLE_TZ.put("America/North_Dakota/New_Salem", -360);
        MOODLE_TZ.put("America/North_Dakota/Beulah", -360);
        MOODLE_TZ.put("America/Denver", -420);
        MOODLE_TZ.put("America/Los_Angeles", -480);
        MOODLE_TZ.put("America/Juneau", -540);
        MOODLE_TZ.put("America/Sitka", -540);
        MOODLE_TZ.put("America/Metlakatla", -540);
        MOODLE_TZ.put("America/Yakutat", -540);
        MOODLE_TZ.put("America/Anchorage", -540);
        MOODLE_TZ.put("America/Nome", -540);
        MOODLE_TZ.put("America/Adak", -600);
        MOODLE_TZ.put("Pacific/Honolulu", -600);
        MOODLE_TZ.put("America/Phoenix", -420);
        MOODLE_TZ.put("America/Boise", -420);
        MOODLE_TZ.put("America/Indiana/Indianapolis", -300);
        MOODLE_TZ.put("America/Indiana/Marengo", -300);
        MOODLE_TZ.put("America/Indiana/Vincennes", -300);
        MOODLE_TZ.put("America/Indiana/Tell_City", -360);
        MOODLE_TZ.put("America/Indiana/Petersburg", -300);
        MOODLE_TZ.put("America/Indiana/Knox", -360);
        MOODLE_TZ.put("America/Indiana/Winamac", -300);
        MOODLE_TZ.put("America/Indiana/Vevay", -300);
        MOODLE_TZ.put("America/Kentucky/Louisville", -300);
        MOODLE_TZ.put("America/Kentucky/Monticello", -300);
        MOODLE_TZ.put("America/Detroit", -300);
        MOODLE_TZ.put("America/Menominee", -360);
        MOODLE_TZ.put("America/St_Johns", -210);
        MOODLE_TZ.put("America/Goose_Bay", -240);
        MOODLE_TZ.put("America/Halifax", -240);
        MOODLE_TZ.put("America/Glace_Bay", -240);
        MOODLE_TZ.put("America/Moncton", -240);
        MOODLE_TZ.put("America/Blanc-Sablon", -240);
        MOODLE_TZ.put("America/Toronto", -300);
        MOODLE_TZ.put("America/Thunder_Bay", -300);
        MOODLE_TZ.put("America/Nipigon", -300);
        MOODLE_TZ.put("America/Rainy_River", -360);
        MOODLE_TZ.put("America/Atikokan", -300);
        MOODLE_TZ.put("America/Winnipeg", -360);
        MOODLE_TZ.put("America/Regina", -360);
        MOODLE_TZ.put("America/Swift_Current", -360);
        MOODLE_TZ.put("America/Edmonton", -420);
        MOODLE_TZ.put("America/Vancouver", -480);
        MOODLE_TZ.put("America/Dawson_Creek", -420);
        MOODLE_TZ.put("America/Fort_Nelson", -420);
        MOODLE_TZ.put("America/Creston", -420);
        MOODLE_TZ.put("America/Pangnirtung", -300);
        MOODLE_TZ.put("America/Iqaluit", -300);
        MOODLE_TZ.put("America/Resolute", -360);
        MOODLE_TZ.put("America/Rankin_Inlet", -360);
        MOODLE_TZ.put("America/Cambridge_Bay", -420);
        MOODLE_TZ.put("America/Yellowknife", -420);
        MOODLE_TZ.put("America/Inuvik", -420);
        MOODLE_TZ.put("America/Whitehorse", -480);
        MOODLE_TZ.put("America/Dawson", -480);
        MOODLE_TZ.put("America/Cancun", -300);
        MOODLE_TZ.put("America/Merida", -360);
        MOODLE_TZ.put("America/Matamoros", -360);
        MOODLE_TZ.put("America/Monterrey", -360);
        MOODLE_TZ.put("America/Mexico_City", -360);
        MOODLE_TZ.put("America/Ojinaga", -420);
        MOODLE_TZ.put("America/Chihuahua", -420);
        MOODLE_TZ.put("America/Hermosillo", -420);
        MOODLE_TZ.put("America/Mazatlan", -420);
        MOODLE_TZ.put("America/Bahia_Banderas", -360);
        MOODLE_TZ.put("America/Tijuana", -480);
        MOODLE_TZ.put("America/Nassau", -300);
        MOODLE_TZ.put("America/Barbados", -240);
        MOODLE_TZ.put("America/Belize", -360);
        MOODLE_TZ.put("Atlantic/Bermuda", -240);
        MOODLE_TZ.put("America/Costa_Rica", -360);
        MOODLE_TZ.put("America/Havana", -300);
        MOODLE_TZ.put("America/Santo_Domingo", -240);
        MOODLE_TZ.put("America/El_Salvador", -360);
        MOODLE_TZ.put("America/Guatemala", -360);
        MOODLE_TZ.put("America/Port-au-Prince", -300);
        MOODLE_TZ.put("America/Tegucigalpa", -360);
        MOODLE_TZ.put("America/Jamaica", -300);
        MOODLE_TZ.put("America/Martinique", -240);
        MOODLE_TZ.put("America/Managua", -360);
        MOODLE_TZ.put("America/Panama", -300);
        MOODLE_TZ.put("America/Puerto_Rico", -240);
        MOODLE_TZ.put("America/Miquelon", -180);
        MOODLE_TZ.put("America/Grand_Turk", -240);
        MOODLE_TZ.put("America/Argentina/Buenos_Aires", -180);
        MOODLE_TZ.put("America/Argentina/Cordoba", -180);
        MOODLE_TZ.put("America/Argentina/Salta", -180);
        MOODLE_TZ.put("America/Argentina/Tucuman", -180);
        MOODLE_TZ.put("America/Argentina/La_Rioja", -180);
        MOODLE_TZ.put("America/Argentina/San_Juan", -180);
        MOODLE_TZ.put("America/Argentina/Jujuy", -180);
        MOODLE_TZ.put("America/Argentina/Catamarca", -180);
        MOODLE_TZ.put("America/Argentina/Mendoza", -180);
        MOODLE_TZ.put("America/Argentina/San_Luis", -180);
        MOODLE_TZ.put("America/Argentina/Rio_Gallegos", -180);
        MOODLE_TZ.put("America/Argentina/Ushuaia", -180);
        MOODLE_TZ.put("America/La_Paz", -240);
        MOODLE_TZ.put("America/Noronha", -120);
        MOODLE_TZ.put("America/Belem", -180);
        MOODLE_TZ.put("America/Santarem", -180);
        MOODLE_TZ.put("America/Fortaleza", -180);
        MOODLE_TZ.put("America/Recife", -180);
        MOODLE_TZ.put("America/Araguaina", -180);
        MOODLE_TZ.put("America/Maceio", -180);
        MOODLE_TZ.put("America/Bahia", -180);
        MOODLE_TZ.put("America/Sao_Paulo", -180);
        MOODLE_TZ.put("America/Campo_Grande", -240);
        MOODLE_TZ.put("America/Cuiaba", -240);
        MOODLE_TZ.put("America/Porto_Velho", -240);
        MOODLE_TZ.put("America/Boa_Vista", -240);
        MOODLE_TZ.put("America/Manaus", -240);
        MOODLE_TZ.put("America/Eirunepe", -300);
        MOODLE_TZ.put("America/Rio_Branco", -300);
        MOODLE_TZ.put("America/Santiago", -240);
        MOODLE_TZ.put("America/Punta_Arenas", -180);
        MOODLE_TZ.put("Pacific/Easter", -360);
        MOODLE_TZ.put("Antarctica/Palmer", -180);
        MOODLE_TZ.put("America/Bogota", -300);
        MOODLE_TZ.put("America/Curacao", -240);
        MOODLE_TZ.put("America/Guayaquil", -300);
        MOODLE_TZ.put("Pacific/Galapagos", -360);
        MOODLE_TZ.put("Atlantic/Stanley", -180);
        MOODLE_TZ.put("America/Cayenne", -180);
        MOODLE_TZ.put("America/Guyana", -240);
        MOODLE_TZ.put("America/Asuncion", -240);
        MOODLE_TZ.put("America/Lima", -300);
        MOODLE_TZ.put("Atlantic/South_Georgia", -120);
        MOODLE_TZ.put("America/Paramaribo", -180);
        MOODLE_TZ.put("America/Port_of_Spain", -240);
        MOODLE_TZ.put("America/Montevideo", -180);
        MOODLE_TZ.put("America/Caracas", -240);
        MOODLE_TZ.put("Etc/GMT", 0);
        MOODLE_TZ.put("Etc/UTC", 0);
        MOODLE_TZ.put("Etc/UCT", 0);
        MOODLE_TZ.put("Etc/GMT-14", -840);
        MOODLE_TZ.put("Etc/GMT-13", -780);
        MOODLE_TZ.put("Etc/GMT-12", -720);
        MOODLE_TZ.put("Etc/GMT-11", -660);
        MOODLE_TZ.put("Etc/GMT-10", -600);
        MOODLE_TZ.put("Etc/GMT-9", -540);
        MOODLE_TZ.put("Etc/GMT-8", -480);
        MOODLE_TZ.put("Etc/GMT-7", -420);
        MOODLE_TZ.put("Etc/GMT-6", -360);
        MOODLE_TZ.put("Etc/GMT-5", -300);
        MOODLE_TZ.put("Etc/GMT-4", -240);
        MOODLE_TZ.put("Etc/GMT-3", -180);
        MOODLE_TZ.put("Etc/GMT-2", -120);
        MOODLE_TZ.put("Etc/GMT-1", -60);
        MOODLE_TZ.put("Etc/GMT+1", 60);
        MOODLE_TZ.put("Etc/GMT+2", 120);
        MOODLE_TZ.put("Etc/GMT+3", 180);
        MOODLE_TZ.put("Etc/GMT+4", 240);
        MOODLE_TZ.put("Etc/GMT+5", 300);
        MOODLE_TZ.put("Etc/GMT+6", 360);
        MOODLE_TZ.put("Etc/GMT+7", 420);
        MOODLE_TZ.put("Etc/GMT+8", 480);
        MOODLE_TZ.put("Etc/GMT+9", 540);
        MOODLE_TZ.put("Etc/GMT+10", 600);
        MOODLE_TZ.put("Etc/GMT+11", 660);
        MOODLE_TZ.put("Etc/GMT+12", 720);
    }
}
